[pop]
node_features = ['p', 'q', 'v', 'theta']
edge_features = ['p','p_or','p_ex','q_or','q_ex','a_or','a_ex','theta_or','theta_ex','rho','cooldown','thermal_limit','timestep_overflow']
enable_expert = true
safe_max_rho = 0.99
actions_per_generator = 10
manager_selective_learning = true
generator_storage_only = true
remove_no_action = true
manager_remove_no_action = true

[agent]
embedding = "egat_architecture_very_very_small"
advantage_stream = "advantage_stream_very_small"
value_stream = "value_stream_very_small"
learning_rate = 1e-5
adam_epsilon = 1.5e-4
learning_frequency = 4
target_network_weight_replace_steps = 100
gamma = 0.99
huber_loss_delta = 2
batch_size = 288


[agent.exploration]
method = "epsilon_greedy"
max_epsilon = 1.0
min_epsilon = 0.01
epsilon_decay = 1750

[agent.replay_memory]
alpha = 0.7
max_beta = 1.0
min_beta = 0.5
annihilation_rate = 875
capacity = 1000

[manager]
embedding = "egat_architecture_very_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-5
adam_epsilon = 1.5e-4
learning_frequency = 4
target_network_weight_replace_steps = 100
gamma = 0.99
huber_loss_delta = 2
batch_size = 288

[manager.exploration]
method = "epsilon_greedy"
max_epsilon = 1.0
min_epsilon = 0.01
epsilon_decay = 1750

[manager.replay_memory]
alpha = 0.7
max_beta = 1.0
min_beta = 0.5
annihilation_rate = 875
capacity = 10000

[head_manager]
embedding = "gat_architecture_small"
advantage_stream = "advantage_stream_small"
value_stream = "value_stream_small"
learning_rate = 1e-5
adam_epsilon = 1.5e-4
learning_frequency = 4
target_network_weight_replace_steps = 100
gamma = 0.99
huber_loss_delta = 2
batch_size = 288

[head_manager.exploration]
method = "epsilon_greedy"
max_epsilon = 1.0
min_epsilon = 0.01
epsilon_decay = 1750

[head_manager.replay_memory]
alpha = 0.7
max_beta = 1.0
min_beta = 0.5
annihilation_rate = 875
capacity = 100000
